resources:
  containers:
    - container: linux_container
      image: oracleinanutshell/oracle-xe-11g

jobs:
  - job: Linux

    pool:
      name: Hosted Ubuntu 1604

    container: linux_container

    steps:
      - task: NodeTool@0
        displayName: "Use Node 10.x"
        inputs:
          versionSpec: 10.x

      - script: npm install
      - script: su root/install
      - script: apt-get install libgtk3.0-0
      - script: npm run test