resources:
  containers:
    - container: win_container
      image: vkarmendra/aspnet-oracle
    - container: linux_container
      image: jeffersonhealth/node-oracle-instantclient

jobs:
  - job: Windows
    pool:
      name: Hosted Windows 2019 with VS2019
      demands: npm

    container: win_container

    steps:
      - task: NodeTool@0
        displayName: "Use Node 10.x"
        inputs:
          versionSpec: 10.x

      - script: npm install
      - script: npm run test