resources:
  containers:
    - container: win_container
      image: mkafifi/windowsoracleclient
    - container: linux_container
      image: jeffersonhealth/node-oracle-instantclient

jobs:
  - job: Windows
    pool:
      name: Hosted Windows 2019 with VS2019
      demands: npm

    container: win_container

    steps:
      - task: NodeTool@0
        displayName: "Use Node 10.x"
        inputs:
          versionSpec: 10.x

      - script: npm install
      - script: npm run test

  - job: Linux

    pool:
      name: Hosted Ubuntu 1604

    container: linux_container

    steps:
      - task: NodeTool@0
        displayName: "Use Node 10.x"
        inputs:
          versionSpec: 10.x
      - script: npm install
      - script: |
          set -e
          /usr/bin/Xvfb :10 -ac >> /tmp/Xvfb.out 2>&1 &
          disown -ar
        displayName: 'Start xvfb'        
      - script: npm run test    
        displayName: 'Run tests'
        env:
          DISPLAY: :10  