resources:
  containers:
    - container: win_container
      image: jturco/oraclecore
    - container: linux_container
      image: jeffersonhealth/node-oracle-instantclient

trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
      containerResource: linux_container
    windows:
      imageName: 'windows-2019'
      containerResource: win_container

pool:
  vmImage: $(imageName)
  demands: npm

container: $[ variables['containerResource'] ]

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- bash: |
    /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    echo ">>> Started xvfb"
    sudo apt-get install -y libX11-xcb
  displayName: Start xvfb
  condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))

- bash: |
    npm install
    npm run test
  displayName: Run Tests
  env:
    DISPLAY: ':99.0'